apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-004608-oa0y-service
spec:
  selector:
    app: enterprise-system-004608-oa0y
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
